project_id = "uaxhhsubbmjqcdelcolw"

[functions.billing-checkout]
verify_jwt = false

[functions.billing-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.deactivate-account]
verify_jwt = false
